# Generated by Django 3.2.6 on 2021-08-22 16:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'email',
                    models.EmailField(
                        max_length=255,
                        unique=True,
                        verbose_name='email address',
                    ),
                ),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=265)),
                (
                    'gender',
                    models.IntegerField(
                        choices=[
                            (9, 'Not Stated'),
                            (1, 'Male'),
                            (2, 'Female'),
                            (3, 'Another Term'),
                        ]
                    ),
                ),
                (
                    'adress',
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    'phone',
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        max_length=128,
                        null=True,
                        region=None,
                        unique=True,
                    ),
                ),
                ('user_class', models.IntegerField(default=11)),
                ('description', models.TextField(default='')),
                ('birth_date', models.DateField()),
                ('created_on', models.DateTimeField()),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('certificate', models.BinaryField(blank=True, null=True)),
                ('profile_pic', models.BinaryField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('title', models.CharField(max_length=24)),
                ('text', models.TextField()),
                ('stars', models.IntegerField()),
                ('created_on', models.DateTimeField()),
                (
                    'author',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='Author',
                        to='user_management.user',
                    ),
                ),
                (
                    'for_user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='for_user',
                        to='user_management.user',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'subject',
                    models.CharField(
                        choices=[
                            (0, 'German'),
                            (1, 'Math'),
                            (2, 'English'),
                            (3, 'Chemestry'),
                            (4, 'Computer Science'),
                        ],
                        max_length=20,
                    ),
                ),
                ('description', models.TextField()),
                ('level_class', models.IntegerField()),
                (
                    'difficulity',
                    models.IntegerField(
                        choices=[(0, 'Beginner'), (1, 'Medium'), (2, 'Hard')]
                    ),
                ),
                ('cost_budget', models.FloatField()),
                ('searching', models.BooleanField()),
                ('created_on', models.DateTimeField()),
                (
                    'author',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='user_management.user',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='UserAuth',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'password',
                    models.CharField(max_length=128, verbose_name='password'),
                ),
                (
                    'last_login',
                    models.DateTimeField(
                        blank=True, null=True, verbose_name='last login'
                    ),
                ),
                (
                    'is_superuser',
                    models.BooleanField(
                        default=False,
                        help_text='Designates that this user has all permissions without explicitly assigning them.',
                        verbose_name='superuser status',
                    ),
                ),
                (
                    'first_name',
                    models.CharField(
                        blank=True, max_length=150, verbose_name='first name'
                    ),
                ),
                (
                    'last_name',
                    models.CharField(
                        blank=True, max_length=150, verbose_name='last name'
                    ),
                ),
                (
                    'is_staff',
                    models.BooleanField(
                        default=False,
                        help_text='Designates whether the user can log into this admin site.',
                        verbose_name='staff status',
                    ),
                ),
                (
                    'is_active',
                    models.BooleanField(
                        default=True,
                        help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.',
                        verbose_name='active',
                    ),
                ),
                (
                    'date_joined',
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name='date joined',
                    ),
                ),
                (
                    'email',
                    models.EmailField(
                        max_length=255,
                        unique=True,
                        verbose_name='email address',
                    ),
                ),
                (
                    'groups',
                    models.ManyToManyField(
                        blank=True,
                        help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.',
                        related_name='user_set',
                        related_query_name='user',
                        to='auth.Group',
                        verbose_name='groups',
                    ),
                ),
                (
                    'user_permissions',
                    models.ManyToManyField(
                        blank=True,
                        help_text='Specific permissions for this user.',
                        related_name='user_set',
                        related_query_name='user',
                        to='auth.Permission',
                        verbose_name='user permissions',
                    ),
                ),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
    ]
