# Generated by Django 3.2.5 on 2021-08-04 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userauth',
            managers=[
            ],
        ),
    ]
