# Generated by Django 3.2.6 on 2021-08-26 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='subject',
            field=models.IntegerField(
                choices=[
                    (0, 'German'),
                    (1, 'Math'),
                    (2, 'English'),
                    (3, 'Chemestry'),
                    (4, 'Computer Science'),
                ]
            ),
        ),
    ]
