# Generated by Django 3.2.5 on 2021-09-10 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_alter_info_cost_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='cost_budget',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
