# Generated by Django 3.2.5 on 2021-10-02 08:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_alter_info_cost_budget'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='difficulity',
            new_name='difficulty',
        ),
        migrations.AddField(
            model_name='settings',
            name='show_email',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='stars',
            field=models.IntegerField(
                validators=[
                    django.core.validators.MaxValueValidator(5),
                    django.core.validators.MinValueValidator(1),
                ]
            ),
        ),
    ]
