# Generated by Django 3.2.6 on 2021-11-02 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_auto_20211102_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='virtual',
            field=models.BooleanField(default=False),
        ),
    ]
