# Generated by Django 3.2.5 on 2021-11-04 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0004_alter_user_phone'),
        ('user_management', '0004_info_virtual'),
    ]

    operations = []
