# Generated by Django 3.2.6 on 2021-10-27 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0004_alter_review_stars'),
        ('user_management', '0005_request'),
    ]

    operations = [
    ]
