# Generated by Django 3.2.6 on 2021-10-27 10:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0006_merge_0004_alter_review_stars_0005_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='level_class',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_class',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(5)]),
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('text', models.TextField()),
                ('ticket_type', models.IntegerField(choices=[(1, 'Report'), (2, 'Bug'), (3, 'Request')])),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_author', to='user_management.user')),
                ('for_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_for_user', to='user_management.user')),
            ],
        ),
    ]
